import Provider from "@/providers/Provider";
import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PublicLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <Provider>
        <body className="antialiased">
          <Header />
          {/* <p className="bg-emerald-200 p-8 text-black ">Navber</p> */}
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
};

export default PublicLayout;
